#!/usr/bin/env bash
set -euo pipefail

usage() {
  echo "usage: render-homebrew-formula.sh <tag> <checksums-file> <output-file>" >&2
}

if [ "$#" -ne 3 ]; then
  usage
  exit 2
fi

tag="$1"
checksums_file="$2"
output_file="$3"
repo_url="https://github.com/herald-email/herald-mail-app"

if [ ! -f "$checksums_file" ]; then
  echo "checksums file not found: ${checksums_file}" >&2
  exit 1
fi

checksum_for() {
  local filename="$1"
  local checksum

  checksum="$(awk -v name="$filename" '$2 == name { print $1 }' "$checksums_file")"
  if [ -z "$checksum" ]; then
    echo "missing checksum for ${filename}" >&2
    exit 1
  fi
  echo "$checksum"
}

arm_asset="herald-${tag}-darwin-arm64.tar.gz"
intel_asset="herald-${tag}-darwin-amd64.tar.gz"
arm_sha="$(checksum_for "$arm_asset")"
intel_sha="$(checksum_for "$intel_asset")"

mkdir -p "$(dirname "$output_file")"

cat >"$output_file" <<EOF
# typed: false
# frozen_string_literal: true

# This file was generated by Herald's release workflow. DO NOT EDIT.
class Herald < Formula
  desc "Terminal email client and inbox cleanup tool"
  homepage "${repo_url}"
  license "FSL-1.1-ALv2"

  on_macos do
    on_arm do
      url "${repo_url}/releases/download/${tag}/${arm_asset}"
      sha256 "${arm_sha}"
    end

    on_intel do
      url "${repo_url}/releases/download/${tag}/${intel_asset}"
      sha256 "${intel_sha}"
    end
  end

  def install
    bin.install "herald"
    bin.install "herald-mcp-server"
    bin.install "herald-ssh-server"
  end

  test do
    system bin/"herald", "--version"
    system bin/"herald", "mcp", "--version"
    system bin/"herald", "ssh", "--version"
    system bin/"herald-mcp-server", "--version"
    system bin/"herald-ssh-server", "--version"

    request = '{"jsonrpc":"2.0","id":1,"method":"tools/list"}'
    assert_match "\"tools\"", shell_output("echo '#{request}' | #{bin}/herald mcp --demo")
  end
end
EOF
