package render

import (
	"fmt"
	htmlstd "html"
	"strconv"
	"strings"

	"github.com/herald-email/herald-mail-app/internal/models"
	"golang.org/x/net/html"
)

// EmailBodyMarkdown returns the terminal-preview Markdown for a received email.
// HTML is preferred because many HTML emails ship a low-fidelity text/plain part
// or a stale fallback generated by the sender.
func EmailBodyMarkdown(body *models.EmailBody) string {
	if body == nil {
		return ""
	}
	if strings.TrimSpace(body.TextHTML) != "" {
		if markdown := strings.TrimSpace(HTMLToMarkdown(body.TextHTML)); markdown != "" {
			return markdown
		}
	}
	return strings.TrimSpace(NormalizeEmailTextArtifacts(body.TextPlain))
}

func EmailBodyMarkdownWithCIDImages(body *models.EmailBody) string {
	if body == nil {
		return ""
	}
	if strings.TrimSpace(body.TextHTML) != "" {
		if markdown := strings.TrimSpace(HTMLToMarkdownWithCIDImages(body.TextHTML)); markdown != "" {
			return markdown
		}
	}
	return strings.TrimSpace(NormalizeEmailTextArtifacts(body.TextPlain))
}

// HTMLToMarkdown converts an HTML string to Markdown suitable for Herald's
// terminal email previews. It intentionally keeps remote images as Markdown
// image links so the terminal renderer can expose readable, safe OSC 8 links.
func HTMLToMarkdown(htmlStr string) string {
	return htmlToMarkdown(htmlStr, htmlMarkdownOptions{})
}

func HTMLToMarkdownWithCIDImages(htmlStr string) string {
	return htmlToMarkdown(htmlStr, htmlMarkdownOptions{keepCIDImages: true, preserveImageSizing: true})
}

type htmlMarkdownOptions struct {
	keepCIDImages       bool
	preserveImageSizing bool
}

func htmlToMarkdown(htmlStr string, opts htmlMarkdownOptions) string {
	doc, err := html.Parse(strings.NewReader(htmlStr))
	if err != nil {
		return html.UnescapeString(stripHTMLTags(htmlStr))
	}

	var out strings.Builder
	pendingNL := 0 // queued newlines (0-2); flushed before the next real text

	addNL := func(n int) {
		if n > pendingNL {
			pendingNL = n
		}
		if pendingNL > 2 {
			pendingNL = 2
		}
	}

	writeText := func(s string) {
		if s == "" {
			return
		}
		if out.Len() > 0 {
			for i := 0; i < pendingNL; i++ {
				out.WriteByte('\n')
			}
			if pendingNL == 0 {
				str := out.String()
				last := str[len(str)-1]
				first := s[0]
				if last != ' ' && last != '\n' && last != '(' && last != '[' &&
					first != ' ' && first != '\n' && first != '.' && first != ',' &&
					first != '!' && first != '?' && first != ')' && first != ']' &&
					first != ':' && first != ';' {
					out.WriteByte(' ')
				}
			}
		}
		pendingNL = 0
		out.WriteString(s)
	}

	var collectText func(*html.Node) string
	collectText = func(n *html.Node) string {
		var sb strings.Builder
		var inner func(*html.Node)
		inner = func(n *html.Node) {
			if n.Type == html.TextNode {
				t := strings.Join(strings.Fields(strings.ReplaceAll(n.Data, "\u00a0", " ")), " ")
				if t != "" {
					if sb.Len() > 0 {
						sb.WriteByte(' ')
					}
					sb.WriteString(t)
				}
			}
			for c := n.FirstChild; c != nil; c = c.NextSibling {
				inner(c)
			}
		}
		inner(n)
		return sb.String()
	}

	var collectTableRows func(*html.Node, *[][]string)
	collectTableRows = func(n *html.Node, rows *[][]string) {
		if n.Type == html.ElementNode && strings.EqualFold(n.Data, "tr") {
			var row []string
			for cell := n.FirstChild; cell != nil; cell = cell.NextSibling {
				if cell.Type != html.ElementNode {
					continue
				}
				if strings.EqualFold(cell.Data, "th") || strings.EqualFold(cell.Data, "td") {
					row = append(row, markdownTableCell(collectText(cell)))
				}
			}
			if len(row) > 0 {
				*rows = append(*rows, row)
			}
			return
		}
		for c := n.FirstChild; c != nil; c = c.NextSibling {
			collectTableRows(c, rows)
		}
	}

	renderDataTable := func(n *html.Node) (string, bool) {
		if isEmailLayoutTable(n) {
			return "", false
		}
		var rows [][]string
		collectTableRows(n, &rows)
		if len(rows) == 0 {
			return "", false
		}
		cols := 0
		for _, row := range rows {
			if len(row) > cols {
				cols = len(row)
			}
		}
		if cols == 0 {
			return "", false
		}
		if !looksLikeDataTable(n, rows, cols) {
			return "", false
		}
		var sb strings.Builder
		writeRow := func(row []string) {
			sb.WriteString("|")
			for i := 0; i < cols; i++ {
				cell := ""
				if i < len(row) {
					cell = row[i]
				}
				sb.WriteString(" ")
				sb.WriteString(cell)
				sb.WriteString(" |")
			}
			sb.WriteByte('\n')
		}
		writeRow(rows[0])
		separator := make([]string, cols)
		for i := range separator {
			separator[i] = "---"
		}
		writeRow(separator)
		for _, row := range rows[1:] {
			writeRow(row)
		}
		return strings.TrimSpace(sb.String()), true
	}

	var walk func(*html.Node)
	walk = func(n *html.Node) {
		switch n.Type {
		case html.TextNode:
			t := strings.ReplaceAll(n.Data, "\u00a0", " ")
			writeText(strings.Join(strings.Fields(t), " "))
			return
		case html.ElementNode:
			tag := strings.ToLower(n.Data)
			switch tag {
			case "style", "script", "head":
				return
			case "img":
				var src, alt, title string
				for _, attr := range n.Attr {
					switch strings.ToLower(attr.Key) {
					case "src":
						src = strings.TrimSpace(attr.Val)
					case "alt":
						alt = strings.TrimSpace(attr.Val)
					case "title":
						title = strings.TrimSpace(attr.Val)
					}
				}
				lowerSrc := strings.ToLower(src)
				if strings.HasPrefix(lowerSrc, "http://") || strings.HasPrefix(lowerSrc, "https://") || (opts.keepCIDImages && strings.HasPrefix(lowerSrc, "cid:")) {
					label := alt
					if label == "" {
						label = title
					}
					if label == "" {
						label = "image"
					}
					if opts.preserveImageSizing {
						if imageHTML, ok := printableMarkdownImageHTML(src, label, n.Attr); ok {
							writeText(imageHTML)
							return
						}
					}
					writeText(fmt.Sprintf("![%s](%s)", escapeMarkdownLabel(label), src))
				}
				return
			case "br":
				addNL(1)
				return
			case "a":
				var href string
				for _, attr := range n.Attr {
					if strings.EqualFold(attr.Key, "href") {
						href = attr.Val
						break
					}
				}
				text := collectText(n)
				if text == "" {
					for c := n.FirstChild; c != nil; c = c.NextSibling {
						walk(c)
					}
					return
				}
				if href != "" && href != "#" && !strings.HasPrefix(strings.ToLower(href), "javascript") {
					writeText(fmt.Sprintf("[%s](%s)", text, href))
				} else {
					writeText(text)
				}
				return
			case "strong", "b":
				text := collectText(n)
				if text != "" {
					writeText("**" + text + "**")
				}
				return
			case "em", "i":
				text := collectText(n)
				if text != "" {
					writeText("*" + text + "*")
				}
				return
			case "code":
				text := collectText(n)
				if text != "" {
					writeText("`" + text + "`")
				}
				return
			case "h1":
				addNL(2)
				writeText("# ")
				for c := n.FirstChild; c != nil; c = c.NextSibling {
					walk(c)
				}
				addNL(2)
				return
			case "h2":
				addNL(2)
				writeText("## ")
				for c := n.FirstChild; c != nil; c = c.NextSibling {
					walk(c)
				}
				addNL(2)
				return
			case "h3", "h4", "h5", "h6":
				addNL(2)
				writeText("### ")
				for c := n.FirstChild; c != nil; c = c.NextSibling {
					walk(c)
				}
				addNL(2)
				return
			case "li":
				addNL(1)
				writeText("- ")
				for c := n.FirstChild; c != nil; c = c.NextSibling {
					walk(c)
				}
				addNL(1)
				return
			case "td", "th":
				for c := n.FirstChild; c != nil; c = c.NextSibling {
					walk(c)
				}
				writeText(" ")
				return
			case "tr":
				for c := n.FirstChild; c != nil; c = c.NextSibling {
					walk(c)
				}
				addNL(1)
				return
			case "table":
				if table, ok := renderDataTable(n); ok {
					addNL(2)
					writeText(table)
				} else {
					addNL(2)
					for c := n.FirstChild; c != nil; c = c.NextSibling {
						walk(c)
					}
				}
				addNL(2)
				return
			default:
				for c := n.FirstChild; c != nil; c = c.NextSibling {
					walk(c)
				}
				switch tag {
				case "p", "div", "section", "article", "blockquote", "ul", "ol":
					addNL(2)
				}
				return
			}
		default:
			for c := n.FirstChild; c != nil; c = c.NextSibling {
				walk(c)
			}
		}
	}
	walk(doc)
	result := out.String()
	for strings.Contains(result, "\n\n\n") {
		result = strings.ReplaceAll(result, "\n\n\n", "\n\n")
	}
	return strings.TrimSpace(NormalizeEmailTextArtifacts(result))
}

func printableMarkdownImageHTML(src, alt string, attrs []html.Attribute) (string, bool) {
	width, height, style := imageSizingHints(attrs)
	if width == "" && height == "" && style == "" {
		return "", false
	}
	var b strings.Builder
	b.WriteString(`<img src="`)
	b.WriteString(htmlstd.EscapeString(src))
	b.WriteString(`" alt="`)
	b.WriteString(htmlstd.EscapeString(alt))
	b.WriteString(`"`)
	if width != "" {
		b.WriteString(` width="`)
		b.WriteString(width)
		b.WriteString(`"`)
	}
	if height != "" {
		b.WriteString(` height="`)
		b.WriteString(height)
		b.WriteString(`"`)
	}
	if style != "" {
		b.WriteString(` style="`)
		b.WriteString(htmlstd.EscapeString(style))
		b.WriteString(`"`)
	}
	b.WriteString(`>`)
	return b.String(), true
}

func imageSizingHints(attrs []html.Attribute) (string, string, string) {
	var width, height, style string
	for _, attr := range attrs {
		key := strings.ToLower(strings.TrimSpace(attr.Key))
		val := strings.TrimSpace(attr.Val)
		switch key {
		case "width":
			if clean, ok := cleanHTMLImageDimension(val); ok {
				width = clean
			}
		case "height":
			if clean, ok := cleanHTMLImageDimension(val); ok {
				height = clean
			}
		case "style":
			style = cleanImageSizingStyle(val)
		}
	}
	return width, height, style
}

func cleanImageSizingStyle(style string) string {
	var out []string
	for _, rawDecl := range strings.Split(style, ";") {
		parts := strings.SplitN(rawDecl, ":", 2)
		if len(parts) != 2 {
			continue
		}
		key := strings.ToLower(strings.TrimSpace(parts[0]))
		val := strings.TrimSpace(parts[1])
		switch key {
		case "width", "max-width", "max-height":
			if clean, ok := cleanCSSImageDimension(val); ok {
				out = append(out, key+":"+clean)
			}
		case "height":
			if strings.EqualFold(strings.TrimSpace(stripCSSImportant(val)), "auto") {
				out = append(out, "height:auto")
				continue
			}
			if clean, ok := cleanCSSImageDimension(val); ok {
				out = append(out, "height:"+clean)
			}
		}
	}
	return strings.Join(out, ";")
}

func cleanHTMLImageDimension(raw string) (string, bool) {
	val := stripCSSImportant(raw)
	if strings.HasSuffix(val, "%") {
		n, ok := parseImageDimensionNumber(strings.TrimSuffix(val, "%"), 100)
		if !ok {
			return "", false
		}
		return formatDimensionNumber(n) + "%", true
	}
	val = strings.TrimSuffix(val, "px")
	n, ok := parseImageDimensionNumber(val, 2400)
	if !ok {
		return "", false
	}
	return formatDimensionNumber(n), true
}

func cleanCSSImageDimension(raw string) (string, bool) {
	val := stripCSSImportant(raw)
	if strings.HasSuffix(val, "%") {
		n, ok := parseImageDimensionNumber(strings.TrimSuffix(val, "%"), 100)
		if !ok {
			return "", false
		}
		return formatDimensionNumber(n) + "%", true
	}
	if strings.HasSuffix(val, "px") {
		n, ok := parseImageDimensionNumber(strings.TrimSuffix(val, "px"), 2400)
		if !ok {
			return "", false
		}
		return formatDimensionNumber(n) + "px", true
	}
	n, ok := parseImageDimensionNumber(val, 2400)
	if !ok {
		return "", false
	}
	return formatDimensionNumber(n) + "px", true
}

func stripCSSImportant(raw string) string {
	val := strings.ToLower(strings.TrimSpace(raw))
	val = strings.ReplaceAll(val, "!important", "")
	return strings.Join(strings.Fields(val), "")
}

func parseImageDimensionNumber(raw string, max float64) (float64, bool) {
	if raw == "" {
		return 0, false
	}
	n, err := strconv.ParseFloat(raw, 64)
	if err != nil || n <= 0 || n > max {
		return 0, false
	}
	return n, true
}

func formatDimensionNumber(n float64) string {
	s := strconv.FormatFloat(n, 'f', 2, 64)
	s = strings.TrimRight(s, "0")
	s = strings.TrimRight(s, ".")
	return s
}

func markdownTableCell(cell string) string {
	cell = strings.Join(strings.Fields(cell), " ")
	cell = strings.ReplaceAll(cell, `\`, `\\`)
	cell = strings.ReplaceAll(cell, "|", `\|`)
	return cell
}

func isEmailLayoutTable(n *html.Node) bool {
	if n == nil || n.Type != html.ElementNode || !strings.EqualFold(n.Data, "table") {
		return false
	}
	for _, attr := range n.Attr {
		key := strings.ToLower(attr.Key)
		val := strings.ToLower(strings.TrimSpace(attr.Val))
		switch key {
		case "role":
			if val == "presentation" || val == "none" {
				return true
			}
		case "style", "class":
			if strings.Contains(val, "presentation") ||
				strings.Contains(val, "container") ||
				strings.Contains(val, "layout") ||
				strings.Contains(val, "wrapper") ||
				strings.Contains(val, "email") {
				return true
			}
		}
	}
	return tableContainsNestedTable(n)
}

func looksLikeDataTable(table *html.Node, rows [][]string, cols int) bool {
	if len(rows) < 2 || cols < 2 {
		return false
	}
	if tableHasHeaderCell(table) {
		return true
	}
	nonEmpty := 0
	longCells := 0
	for _, row := range rows {
		for _, cell := range row {
			cell = strings.TrimSpace(cell)
			if cell == "" {
				continue
			}
			nonEmpty++
			if len([]rune(cell)) > 80 {
				longCells++
			}
		}
	}
	return nonEmpty >= len(rows)*2 && longCells == 0
}

func tableContainsNestedTable(n *html.Node) bool {
	if n == nil {
		return false
	}
	for c := n.FirstChild; c != nil; c = c.NextSibling {
		if c.Type == html.ElementNode && strings.EqualFold(c.Data, "table") {
			return true
		}
		if tableContainsNestedTable(c) {
			return true
		}
	}
	return false
}

func tableHasHeaderCell(n *html.Node) bool {
	if n == nil {
		return false
	}
	if n.Type == html.ElementNode && strings.EqualFold(n.Data, "th") {
		return true
	}
	for c := n.FirstChild; c != nil; c = c.NextSibling {
		if tableHasHeaderCell(c) {
			return true
		}
	}
	return false
}

func stripHTMLTags(s string) string {
	var sb strings.Builder
	inTag := false
	for _, r := range s {
		switch {
		case r == '<':
			inTag = true
		case r == '>':
			inTag = false
		case !inTag:
			sb.WriteRune(r)
		}
	}
	return sb.String()
}
