package render

import (
	"fmt"
	"strings"

	"golang.org/x/net/html"
	"mail-processor/internal/models"
)

// EmailBodyMarkdown returns the terminal-preview Markdown for a received email.
// HTML is preferred because many HTML emails ship a low-fidelity text/plain part
// or a stale fallback generated by the sender.
func EmailBodyMarkdown(body *models.EmailBody) string {
	if body == nil {
		return ""
	}
	if strings.TrimSpace(body.TextHTML) != "" {
		if markdown := strings.TrimSpace(HTMLToMarkdown(body.TextHTML)); markdown != "" {
			return markdown
		}
	}
	return strings.TrimSpace(body.TextPlain)
}

// HTMLToMarkdown converts an HTML string to Markdown suitable for Herald's
// terminal email previews. It intentionally keeps remote images as Markdown
// image links so the terminal renderer can expose readable, safe OSC 8 links.
func HTMLToMarkdown(htmlStr string) string {
	doc, err := html.Parse(strings.NewReader(htmlStr))
	if err != nil {
		return html.UnescapeString(stripHTMLTags(htmlStr))
	}

	var out strings.Builder
	pendingNL := 0 // queued newlines (0-2); flushed before the next real text

	addNL := func(n int) {
		if n > pendingNL {
			pendingNL = n
		}
		if pendingNL > 2 {
			pendingNL = 2
		}
	}

	writeText := func(s string) {
		if s == "" {
			return
		}
		if out.Len() > 0 {
			for i := 0; i < pendingNL; i++ {
				out.WriteByte('\n')
			}
			if pendingNL == 0 {
				str := out.String()
				last := str[len(str)-1]
				first := s[0]
				if last != ' ' && last != '\n' && last != '(' && last != '[' &&
					first != ' ' && first != '\n' && first != '.' && first != ',' &&
					first != '!' && first != '?' && first != ')' && first != ']' &&
					first != ':' && first != ';' {
					out.WriteByte(' ')
				}
			}
		}
		pendingNL = 0
		out.WriteString(s)
	}

	var collectText func(*html.Node) string
	collectText = func(n *html.Node) string {
		var sb strings.Builder
		var inner func(*html.Node)
		inner = func(n *html.Node) {
			if n.Type == html.TextNode {
				t := strings.Join(strings.Fields(strings.ReplaceAll(n.Data, "\u00a0", " ")), " ")
				if t != "" {
					if sb.Len() > 0 {
						sb.WriteByte(' ')
					}
					sb.WriteString(t)
				}
			}
			for c := n.FirstChild; c != nil; c = c.NextSibling {
				inner(c)
			}
		}
		inner(n)
		return sb.String()
	}

	var collectTableRows func(*html.Node, *[][]string)
	collectTableRows = func(n *html.Node, rows *[][]string) {
		if n.Type == html.ElementNode && strings.EqualFold(n.Data, "tr") {
			var row []string
			for cell := n.FirstChild; cell != nil; cell = cell.NextSibling {
				if cell.Type != html.ElementNode {
					continue
				}
				if strings.EqualFold(cell.Data, "th") || strings.EqualFold(cell.Data, "td") {
					row = append(row, markdownTableCell(collectText(cell)))
				}
			}
			if len(row) > 0 {
				*rows = append(*rows, row)
			}
			return
		}
		for c := n.FirstChild; c != nil; c = c.NextSibling {
			collectTableRows(c, rows)
		}
	}

	renderTable := func(n *html.Node) string {
		var rows [][]string
		collectTableRows(n, &rows)
		if len(rows) == 0 {
			return ""
		}
		cols := 0
		for _, row := range rows {
			if len(row) > cols {
				cols = len(row)
			}
		}
		if cols == 0 {
			return ""
		}
		var sb strings.Builder
		writeRow := func(row []string) {
			sb.WriteString("|")
			for i := 0; i < cols; i++ {
				cell := ""
				if i < len(row) {
					cell = row[i]
				}
				sb.WriteString(" ")
				sb.WriteString(cell)
				sb.WriteString(" |")
			}
			sb.WriteByte('\n')
		}
		writeRow(rows[0])
		separator := make([]string, cols)
		for i := range separator {
			separator[i] = "---"
		}
		writeRow(separator)
		for _, row := range rows[1:] {
			writeRow(row)
		}
		return strings.TrimSpace(sb.String())
	}

	var walk func(*html.Node)
	walk = func(n *html.Node) {
		switch n.Type {
		case html.TextNode:
			t := strings.ReplaceAll(n.Data, "\u00a0", " ")
			writeText(strings.Join(strings.Fields(t), " "))
			return
		case html.ElementNode:
			tag := strings.ToLower(n.Data)
			switch tag {
			case "style", "script", "head":
				return
			case "img":
				var src, alt, title string
				for _, attr := range n.Attr {
					switch strings.ToLower(attr.Key) {
					case "src":
						src = strings.TrimSpace(attr.Val)
					case "alt":
						alt = strings.TrimSpace(attr.Val)
					case "title":
						title = strings.TrimSpace(attr.Val)
					}
				}
				lowerSrc := strings.ToLower(src)
				if strings.HasPrefix(lowerSrc, "http://") || strings.HasPrefix(lowerSrc, "https://") {
					label := alt
					if label == "" {
						label = title
					}
					if label == "" {
						label = "image"
					}
					writeText(fmt.Sprintf("![%s](%s)", escapeMarkdownLabel(label), src))
				}
				return
			case "br":
				addNL(1)
				return
			case "a":
				var href string
				for _, attr := range n.Attr {
					if strings.EqualFold(attr.Key, "href") {
						href = attr.Val
						break
					}
				}
				text := collectText(n)
				if text == "" {
					for c := n.FirstChild; c != nil; c = c.NextSibling {
						walk(c)
					}
					return
				}
				if href != "" && href != "#" && !strings.HasPrefix(strings.ToLower(href), "javascript") {
					writeText(fmt.Sprintf("[%s](%s)", text, href))
				} else {
					writeText(text)
				}
				return
			case "strong", "b":
				text := collectText(n)
				if text != "" {
					writeText("**" + text + "**")
				}
				return
			case "em", "i":
				text := collectText(n)
				if text != "" {
					writeText("*" + text + "*")
				}
				return
			case "code":
				text := collectText(n)
				if text != "" {
					writeText("`" + text + "`")
				}
				return
			case "h1":
				addNL(2)
				writeText("# ")
				for c := n.FirstChild; c != nil; c = c.NextSibling {
					walk(c)
				}
				addNL(2)
				return
			case "h2":
				addNL(2)
				writeText("## ")
				for c := n.FirstChild; c != nil; c = c.NextSibling {
					walk(c)
				}
				addNL(2)
				return
			case "h3", "h4", "h5", "h6":
				addNL(2)
				writeText("### ")
				for c := n.FirstChild; c != nil; c = c.NextSibling {
					walk(c)
				}
				addNL(2)
				return
			case "li":
				addNL(1)
				writeText("- ")
				for c := n.FirstChild; c != nil; c = c.NextSibling {
					walk(c)
				}
				addNL(1)
				return
			case "td", "th":
				for c := n.FirstChild; c != nil; c = c.NextSibling {
					walk(c)
				}
				writeText(" ")
				return
			case "tr":
				for c := n.FirstChild; c != nil; c = c.NextSibling {
					walk(c)
				}
				addNL(1)
				return
			case "table":
				addNL(2)
				writeText(renderTable(n))
				addNL(2)
				return
			default:
				for c := n.FirstChild; c != nil; c = c.NextSibling {
					walk(c)
				}
				switch tag {
				case "p", "div", "section", "article", "blockquote", "ul", "ol":
					addNL(2)
				}
				return
			}
		default:
			for c := n.FirstChild; c != nil; c = c.NextSibling {
				walk(c)
			}
		}
	}
	walk(doc)
	result := out.String()
	for strings.Contains(result, "\n\n\n") {
		result = strings.ReplaceAll(result, "\n\n\n", "\n\n")
	}
	return strings.TrimSpace(result)
}

func markdownTableCell(cell string) string {
	cell = strings.Join(strings.Fields(cell), " ")
	cell = strings.ReplaceAll(cell, `\`, `\\`)
	cell = strings.ReplaceAll(cell, "|", `\|`)
	return cell
}

func stripHTMLTags(s string) string {
	var sb strings.Builder
	inTag := false
	for _, r := range s {
		switch {
		case r == '<':
			inTag = true
		case r == '>':
			inTag = false
		case !inTag:
			sb.WriteRune(r)
		}
	}
	return sb.String()
}
